# -*- coding: utf-8 -*-
"""Prueba3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UtfYNd25kL16-VfCSxicOuVFUY0X_F8X
"""

import streamlit as st

st.write('Hello *World!* :sunglases:')